services:
  flight-db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: flight_db
    environment:
      SA_PASSWORD: 'abc!123ABC'
      ACCEPT_EULA: 'Y'
    ports:
      - '1434:1433'
    restart: always
    volumes:
      - ./server/ms_flight_data:/var/opt/mssql/data
    networks:
      - flight-backend

networks:
  flight-backend:
    driver: bridge
